reduction_url_redirect:
    path: /redirect/{code}
    defaults: { _controller: AppBundle:Redirect:index }
    methods: GET
    options:
        expose: true
    requirements:
        code: \S+

reduction_url_encode:
    path: /url
    defaults: { _controller: AppBundle:Encode:index }
    options:
        expose: true
    methods: POST

reduction_main:
    path: /main
    defaults: { _controller: AppBundle:Main:index }
    methods: GET

